// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export const adminConsoleNavigation = [
    {
        type: ['team', 'e20'],
        header: 'Edition and License',
        sidebar: 'Edition and License',
        url: 'admin_console/about/license',
    },
    {
        type: ['team', 'e20'],
        header: 'System Statistics',
        sidebar: 'Site Statistics',
        url: '/admin_console/reporting/system_analytics',
    },
    {
        type: ['team', 'e20'],
        header: 'Team Statistics',
        sidebar: 'Team Statistics',
        url: '/admin_console/reporting/team_statistics',
        headerContains: true,
    },
    {
        type: ['team', 'e20'],
        header: 'Server Logs',
        sidebar: 'Server Logs',
        url: '/admin_console/reporting/server_logs',
        headerContains: true,
    },
    {
        type: ['team', 'e20'],
        header: 'Mattermost Users',
        headerSelector: '.admin-console__header #systemUsersTable-headerId',
        sidebar: 'Users',
        url: 'admin_console/user_management/users',
    },
    {
        type: ['team', 'e20'],
        header: 'Groups',
        sidebar: 'Groups',
        url: 'admin_console/user_management/groups',
    },
    {
        type: ['team', 'e20'],
        header: 'Mattermost Teams',
        sidebar: 'Teams',
        url: 'admin_console/user_management/teams',
    },
    {
        type: ['team', 'e20'],
        header: 'Mattermost Channels',
        team_header: 'Channels',
        sidebar: 'Channels',
        url: 'admin_console/user_management/channels',
    },
    {
        type: ['team', 'e20'],
        header: 'Permission Schemes',
        sidebar: 'Permissions',
        url: 'admin_console/user_management/permissions',
    },
    {
        type: ['team', 'e20'],
        header: 'Delegated Granular Administration',
        sidebar: 'Delegated Granular Administration',
        url: 'admin_console/user_management/system_roles',
    },
    {
        type: ['team', 'e20'],
        header: 'Web Server',
        sidebar: 'Web Server',
        url: 'admin_console/environment/web_server',
    },
    {
        type: ['team', 'e20'],
        header: 'Database',
        sidebar: 'Database',
        url: 'admin_console/environment/database',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'File Storage',
        sidebar: 'File Storage',
        url: 'admin_console/environment/file_storage',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Image Proxy',
        sidebar: 'Image Proxy',
        url: 'admin_console/environment/image_proxy',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'SMTP',
        sidebar: 'SMTP',
        url: 'admin_console/environment/smtp',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Push Notification Server',
        sidebar: 'Push Notification Server',
        url: 'admin_console/environment/push_notification_server',
    },
    {
        type: ['e20'],
        section: 'Environment',
        header: 'High Availability',
        sidebar: 'High Availability',
        url: 'admin_console/environment/high_availability',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Rate Limiting',
        sidebar: 'Rate Limiting',
        url: 'admin_console/environment/rate_limiting',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Logging',
        sidebar: 'Logging',
        url: 'admin_console/environment/logging',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Session Lengths',
        sidebar: 'Session Lengths',
        url: 'admin_console/environment/session_lengths',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Performance Monitoring',
        sidebar: 'Performance Monitoring',
        url: 'admin_console/environment/performance_monitoring',
    },
    {
        type: ['team', 'e20'],
        section: 'Environment',
        header: 'Developer Settings',
        sidebar: 'Developer',
        url: 'admin_console/environment/developer',
    },
    {
        type: ['team', 'e20'],
        header: 'Customization',
        sidebar: 'Customization',
        url: 'admin_console/site_config/customization',
    },
    {
        type: ['team', 'e20'],
        header: 'Localization',
        sidebar: 'Localization',
        url: 'admin_console/site_config/localization',
    },
    {
        type: ['team', 'e20'],
        header: 'Users and Teams',
        sidebar: 'Users and Teams',
        url: 'admin_console/site_config/users_and_teams',
    },
    {
        type: ['team', 'e20'],
        header: 'Notifications',
        sidebar: 'Notifications',
        url: 'admin_console/environment/notifications',
    },
    {
        type: ['team', 'e20'],
        header: 'Announcement Banner',
        sidebar: 'Announcement Banner',
        url: 'admin_console/site_config/announcement_banner',
    },
    {
        type: ['team', 'e20'],
        header: 'Emoji',
        sidebar: 'Emoji',
        url: 'admin_console/site_config/emoji',
    },
    {
        type: ['team', 'e20'],
        header: 'Posts',
        sidebar: 'Posts',
        url: 'admin_console/site_config/posts',
    },
    {
        type: ['team', 'e20'],
        header: 'File Sharing and Downloads',
        sidebar: 'File Sharing and Downloads',
        url: 'admin_console/site_config/file_sharing_downloads',
    },
    {
        type: ['team', 'e20'],
        header: 'Public Links',
        sidebar: 'Public Links',
        url: 'admin_console/site_config/public_links',
    },
    {
        type: ['team', 'e20'],
        header: 'Notices',
        sidebar: 'Notices',
        url: 'admin_console/site_config/notices',
    },
    {
        type: ['team', 'e20'],
        header: 'Signup',
        sidebar: 'Signup',
        url: 'admin_console/authentication/signup',
    },
    {
        type: ['team', 'e20'],
        header: 'Email',
        sidebar: 'Email',
        url: 'admin_console/authentication/email',
    },
    {
        type: ['team', 'e20'],
        header: 'Password',
        sidebar: 'Password',
        url: 'admin_console/authentication/password',
    },
    {
        type: ['team', 'e20'],
        header: 'Multi-factor Authentication',
        sidebar: 'MFA',
        url: 'admin_console/authentication/mfa',
    },
    {
        type: ['team', 'e20'],
        header: 'AD/LDAP Wizard',
        sidebar: 'AD/LDAP',
        url: 'admin_console/authentication/ldap',
    },
    {
        type: ['team', 'e20'],
        header: 'SAML 2.0',
        sidebar: 'SAML 2.0',
        url: 'admin_console/authentication/saml',
    },
    {
        type: ['team'],
        header: 'GitLab',
        sidebar: 'GitLab',
        url: 'admin_console/authentication/gitlab',
    },
    {
        type: ['team', 'e20'],
        header: 'OpenID Connect',
        sidebar: 'OpenID Connect',
        url: 'admin_console/authentication/openid',
    },
    {
        type: ['team', 'e20'],
        header: 'Guest Access',
        sidebar: 'Guest Access',
        url: 'admin_console/authentication/guest_access',
    },
    {
        type: ['team', 'e20'],
        header: 'Integration Management',
        sidebar: 'Integration Management',
        url: 'admin_console/integrations/integration_management',
    },
    {
        type: ['team', 'e20'],
        header: 'Bot Accounts',
        sidebar: 'Bot Accounts',
        url: 'admin_console/integrations/bot_accounts',
    },
    {
        type: ['team', 'e20'],
        header: 'CORS',
        sidebar: 'CORS',
        url: 'admin_console/integrations/cors',
    },
    {
        type: ['e20'],
        header: 'Data Retention Policies',
        sidebar: 'Data Retention Policies',
        url: 'admin_console/compliance/data_retention_settings',
    },
    {
        type: ['team'],
        header: 'Data Retention Policy',
        sidebar: 'Data Retention Policy',
        url: 'admin_console/compliance/data_retention',
    },
    {
        type: ['team', 'e20'],
        header: 'Compliance Export',
        sidebar: 'Compliance Export',
        url: 'admin_console/compliance/export',
    },
    {
        type: ['e20'],
        header: 'Compliance Monitoring',
        sidebar: 'Compliance Monitoring',
        url: 'admin_console/compliance/monitoring',
    },
    {
        type: ['team', 'e20'],
        header: 'Custom Terms of Service',
        sidebar: 'Custom Terms of Service',
        url: 'admin_console/compliance/custom_terms_of_service',
    },
    {
        type: ['team', 'e20'],
        header: 'Experimental Features',
        sidebar: 'Features',
        url: 'admin_console/experimental/features',
    },
    {
        type: ['team', 'e20'],
        header: 'Feature Flags',
        sidebar: 'Feature Flags',
        url: 'admin_console/experimental/feature_flags',
    },
];
