## Upload sentry results when Server CI Master is completed
name: Sentry Upload

on:
  workflow_run:
    workflows:
      - "Server CI"
    types:
      - completed

permissions:
  contents: read

jobs:
  sentry:
    name: Send build info to sentry
    runs-on: ubuntu-22.04
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.MM_SERVER_SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.MM_SERVER_SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.MM_SERVER_SENTRY_PROJECT }}
    steps:
      - name: cd/Checkout mattermost project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: cd/Create Sentry release
        uses: getsentry/action-release@ff07929a6537bac57790c3451cf4d364aca38528 # v3.7.0

